/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gustavo.view;
import javax.swing.GroupLayout.Alignment;

import java.sql.SQLException;

import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import com.gustavo.DAO.AnimalDAO;
import com.gustavo.DAO.VacinaDAO;
import com.gustavo.control.ExceptionDAO;
import com.gustavo.control.VacinaControl;
import com.gustavo.model.Animais;
import com.gustavo.model.Vacina;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Toolkit;

/**
 *
 * @author Gusta
 */
public class telaCadastroVacina extends javax.swing.JFrame {

	/**
	 * Creates new form telaCadastroVacina
	 */
	public telaCadastroVacina() {
		setIconImage(Toolkit.getDefaultToolkit().getImage(telaCadastroVacina.class.getResource("/imagens/animal-care.png")));
		initComponents();
		PreencherCombo();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		jTextField1 = new javax.swing.JTextField();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTFNomeVacina = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				cadastrarVacina();

			}
		});
		jBTNVoltar = new javax.swing.JButton();
		jTFDia = new javax.swing.JTextField();
		jTFMes = new javax.swing.JTextField();
		jTFAno = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();

		jTextField1.setText("jTextField1");

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

		jLabel1.setText("ID Pet:");

		jLabel2.setText("Nome:");

		jLabel3.setText("Data aplicação");

		jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gusta\\Documents\\NetBeansProjects\\FrontEndDesktop\\src\\main\\java\\imagens\\salvar.png")); // NOI18N
		jButton1.setText("Salvar");

		jBTNVoltar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gusta\\Documents\\NetBeansProjects\\FrontEndDesktop\\src\\main\\java\\imagens\\de-volta.png")); // NOI18N
		jBTNVoltar.setText("Voltar");
		jBTNVoltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBTNVoltarActionPerformed(evt);
			}
		});

		jLabel4.setText("Dia:");

		jLabel6.setText("Mês");

		jLabel7.setText("Ano");

		jCBIdPet = new JComboBox();

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(27)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(16)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
												.addComponent(jLabel4)
												.addComponent(jLabel1)
												.addComponent(jLabel2))
										.addGap(4)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(jLabel6)
														.addGap(48)
														.addComponent(jLabel7))
												.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
														.addPreferredGap(ComponentPlacement.RELATED)
														.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
																.addComponent(jTFNomeVacina, GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
																.addComponent(jCBIdPet, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
										.addGap(10, 25, Short.MAX_VALUE))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(12)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(jButton1)
														.addPreferredGap(ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
														.addComponent(jBTNVoltar))
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
																.addComponent(jLabel3)
																.addGroup(jPanel1Layout.createSequentialGroup()
																		.addComponent(jTFDia, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
																		.addGap(18)
																		.addComponent(jTFMes, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)))
														.addPreferredGap(ComponentPlacement.UNRELATED)
														.addComponent(jTFAno, GroupLayout.PREFERRED_SIZE, 61, Short.MAX_VALUE)))))
						.addGap(27))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel1)
								.addComponent(jCBIdPet, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(24)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(jLabel2)
								.addComponent(jTFNomeVacina, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(30)
						.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGap(11)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
												.addComponent(jLabel6)
												.addComponent(jLabel7))
										.addPreferredGap(ComponentPlacement.RELATED)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
												.addComponent(jTFMes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addComponent(jTFAno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addComponent(jTFDia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
										.addGap(18)
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
												.addComponent(jButton1)
												.addComponent(jBTNVoltar)))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addPreferredGap(ComponentPlacement.UNRELATED)
										.addComponent(jLabel4)))
						.addContainerGap())
				);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
				);

		pack();
	}// </editor-fold>                        

	private void jBTNVoltarActionPerformed(java.awt.event.ActionEvent evt) {                                           
		// TODO add your handling code here:
		telaCadastroVacina.this.dispose();
		telaConsultaCarteiraPet frame = new telaConsultaCarteiraPet();
		frame.setVisible(true);
	}                    

	public void PreencherCombo() {
		try {
			AnimalDAO animal = new AnimalDAO();

			for (Animais a : animal.carregandoID()) {
				jCBIdPet.addItem(a.getIdPet());
			}
		} catch (ExceptionDAO | SQLException e) {
			e.printStackTrace();
		}
	}
	public void cadastrarVacina() {
		boolean sucesso;
		try {
			VacinaControl vacinaControl = new VacinaControl();
			String dia,mes,ano, dataFinal;
			String nome = jTFNomeVacina.getText();
			dia = jTFDia.getText();
			mes = jTFMes.getText();
			ano = jTFAno.getText();
			if(dia.length()!=2 || mes.length()!=2||ano.length()!=4) {
				JOptionPane.showMessageDialog(null, "O formato da data é invalido, formato valido : dd/mm/yyyy");
			}else {
				dataFinal = dia + "/" + mes +"/" + ano;
				int cboIdPet = (int) jCBIdPet.getSelectedItem();
				System.out.println(cboIdPet);
				sucesso = VacinaControl.cadastrarVacina(nome, dataFinal, cboIdPet );
				System.out.println(sucesso);
				if (sucesso == true) {

					JOptionPane.showMessageDialog(null, "Vacina cadastrada com sucesso");

				} else if (nome.length() <= 0 || dataFinal.length() <= 0|| cboIdPet!=0) {
					JOptionPane.showMessageDialog(null, "Preencha todos os campos");
				}
			}
		} catch (Exception ex) {
			ex.printStackTrace();
			JOptionPane.showMessageDialog(null, "Erro ao cadastrar Vacina");
		}
	}
	/**
	 * @param args the command line arguments
	 */
	//    public static void main(String args[]) {
	//        /* Set the Nimbus look and feel */
	//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	//         */
	//        try {
	//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	//                if ("Nimbus".equals(info.getName())) {
	//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	//                    break;
	//                }
	//            }
	//        } catch (ClassNotFoundException ex) {
	//            java.util.logging.Logger.getLogger(telaCadastroVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	//        } catch (InstantiationException ex) {
	//            java.util.logging.Logger.getLogger(telaCadastroVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	//        } catch (IllegalAccessException ex) {
	//            java.util.logging.Logger.getLogger(telaCadastroVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	//            java.util.logging.Logger.getLogger(telaCadastroVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	//        }
	//        //</editor-fold>
	//
	//        /* Create and display the form */
	//        java.awt.EventQueue.invokeLater(new Runnable() {
	//            public void run() {
	//                new telaCadastroVacina().setVisible(true);
	//            }
	//        });
	//    }

	// Variables declaration - do not modify                     
	private javax.swing.JButton jBTNVoltar;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTFAno;
	private javax.swing.JTextField jTFDia;
	private javax.swing.JTextField jTFMes;
	private javax.swing.JTextField jTFNomeVacina;
	private javax.swing.JTextField jTextField1;
	private JComboBox jCBIdPet;
}
