/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gustavo.view;
import javax.swing.GroupLayout.Alignment;

import java.sql.SQLException;

import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import com.gustavo.DAO.VacinaDAO;
import com.gustavo.DAO.VacinaDAO;
import com.gustavo.control.ExceptionDAO;
import com.gustavo.control.VacinaControl;
import com.gustavo.model.Cliente;
import com.gustavo.model.Vacina;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;
import java.awt.Toolkit;

/**
 *
 * @author Gusta
 */
public class telaAlterarVacina extends javax.swing.JFrame {
	private JComboBox jCBIdVacina;
	/**
	 * Creates new form telaCadastroVacina
	 */
	public telaAlterarVacina() {
		setIconImage(Toolkit.getDefaultToolkit().getImage(telaAlterarVacina.class.getResource("/imagens/animal-care.png")));
		initComponents();
		PreencherCombo();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		jTextField1 = new javax.swing.JTextField();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jTFNome = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jBTNVoltar = new javax.swing.JButton();
		jTFDia = new javax.swing.JTextField();
		jTFMes = new javax.swing.JTextField();
		jTFAno = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jCBIdVacina = new JComboBox();
		jTextField1.setText("jTextField1");

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

		jLabel2.setText("Nome:");

		jLabel3.setText("Data aplicação");

		jButton1.setIcon(new ImageIcon(telaAlterarVacina.class.getResource("/imagens/salvar.png"))); // NOI18N
		jButton1.setText("Salvar");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel4.setText("ID Vacina");

		jBTNVoltar.setIcon(new ImageIcon(telaAlterarVacina.class.getResource("/imagens/de-volta.png"))); // NOI18N
		jBTNVoltar.setText("Voltar");
		jBTNVoltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBTNVoltarActionPerformed(evt);
			}
		});

		jLabel1.setText("Dia");

		jLabel5.setText("Mês:");

		jLabel6.setText("Ano:");



		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(55)
						.addComponent(jLabel1)
						.addGap(66)
						.addComponent(jLabel5)
						.addPreferredGap(ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
						.addComponent(jLabel6)
						.addGap(29))
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(34)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(jButton1)
										.addPreferredGap(ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
										.addComponent(jBTNVoltar))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addComponent(jTFDia, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
														.addGap(18)
														.addComponent(jTFMes, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
														.addComponent(jTFAno, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE))
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
																.addComponent(jLabel4, Alignment.TRAILING)
																.addComponent(jLabel2, Alignment.TRAILING))
														.addGap(18)
														.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
																.addComponent(jLabel3)
																.addComponent(jTFNome, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
																.addComponent(jCBIdVacina, GroupLayout.PREFERRED_SIZE, 131, GroupLayout.PREFERRED_SIZE))))
										.addContainerGap())))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(27)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(jLabel4)
								.addComponent(jCBIdVacina, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jTFNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(jLabel3)
						.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel1)
								.addComponent(jLabel6)
								.addComponent(jLabel5))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jTFDia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jTFAno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jTFMes, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(33)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jBTNVoltar)
								.addComponent(jButton1)))
				);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
				layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(Alignment.LEADING, layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 293, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(25, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
				);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>                        

	private void jBTNVoltarActionPerformed(java.awt.event.ActionEvent evt) {                                           
		telaAlterarVacina.this.dispose();
		telaConsultaCarteiraPet frame = new telaConsultaCarteiraPet();
		frame.setVisible(true);
	}                                          

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		alterarVacina();
	}                                        

	/**
	 * @param args the command line arguments
	 */
	//    public static void main(String args[]) {
	//        /* Set the Nimbus look and feel */
	//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	//         */
	//        try {
	//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	//                if ("Nimbus".equals(info.getName())) {
	//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	//                    break;
	//                }
	//            }
	//        } catch (ClassNotFoundException ex) {
	//            java.util.logging.Logger.getLogger(telaAlterarVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	//        } catch (InstantiationException ex) {
	//            java.util.logging.Logger.getLogger(telaAlterarVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	//        } catch (IllegalAccessException ex) {
	//            java.util.logging.Logger.getLogger(telaAlterarVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	//            java.util.logging.Logger.getLogger(telaAlterarVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	//        }
	//        //</editor-fold>
	//        //</editor-fold>
	//
	//        /* Create and display the form */
	//        java.awt.EventQueue.invokeLater(new Runnable() {
	//            public void run() {
	//                new telaAlterarVacina().setVisible(true);
	//            }
	//        });
	//    }

	public void PreencherCombo() {
		try {
			VacinaDAO vacina = new VacinaDAO();

			for (Vacina v : vacina.carregandoID()) {
				jCBIdVacina.addItem(v.getCodigo());
			}
		} catch (ExceptionDAO | SQLException e) {
			e.printStackTrace();
		}
	}

	public void alterarVacina() {
		boolean sucesso;
		try {
			VacinaControl vacinaControl = new VacinaControl();
			String dia,mes,ano, dataFinal;
			String nome = jTFNome.getText();
			dia = jTFDia.getText();
			mes = jTFMes.getText();
			ano = jTFAno.getText();
			if(dia.length()!=2 || mes.length()!=2||ano.length()!=4) {
				JOptionPane.showMessageDialog(null, "O formato da data é invalido, formato valido : dd/mm/yyyy");
			}else {
				dataFinal = dia + "/" + mes +"/" + ano;
				if(jCBIdVacina.getSelectedItem() == null) {
					int cboVacina = 0;
					sucesso = VacinaControl.alterarVacina(nome,dataFinal, cboVacina);
					System.out.println(sucesso);
					if (sucesso == true) {

						JOptionPane.showMessageDialog(null, "Vacina alterado com sucesso");

					} else if ( cboVacina == 0) {
						JOptionPane.showMessageDialog(null, "Nenhum ID de vacina selecionado");
					}

				}else {
					int cboVacina = (int) jCBIdVacina.getSelectedItem();

					sucesso = VacinaControl.alterarVacina(nome,dataFinal, cboVacina);
					System.out.println(sucesso);
					if (sucesso == true) {

						JOptionPane.showMessageDialog(null, "Vacina alterado com sucesso");

					} else if (nome.length() <= 0 || dataFinal.length() <= 0|| cboVacina == 0) {
						JOptionPane.showMessageDialog(null, "Preencha todos os campos");
					}
				}}
		} catch (Exception ex) {
			ex.printStackTrace();
			JOptionPane.showMessageDialog(null, "Erro ao alterar Vacina");
		}
	}

	// Variables declaration - do not modify        
	//	private javax.swing.JComboBox jCBIdVacina;
	private javax.swing.JButton jBTNVoltar;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTFAno;
	private javax.swing.JTextField jTFDia;
	private javax.swing.JTextField jTFMes;
	private javax.swing.JTextField jTFNome;
	private javax.swing.JTextField jTextField1;
}
