/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gustavo.view;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import com.gustavo.DAO.ClienteDAO;
import com.gustavo.control.AnimaisControl;
import com.gustavo.control.ClienteControl;
import com.gustavo.control.ExceptionDAO;
import com.gustavo.model.Animais;
import com.gustavo.model.Cliente;


import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JTextField;
import java.awt.Toolkit;

/**
 *
 * @author Gusta
 */
public class telaCadastrarPet extends javax.swing.JFrame {
	private JComboBox jCBCpfDono;
	/**
	 * Creates new form telaCadastrarPet
	 */
	public telaCadastrarPet() {
		setIconImage(Toolkit.getDefaultToolkit().getImage(telaCadastrarPet.class.getResource("/imagens/animal-care.png")));
		initComponents();
		PreencherCombo();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jTFNome = new javax.swing.JTextField();
		jTFRaca = new javax.swing.JTextField();
		jTFEspecie = new javax.swing.JTextField();
		jCBCpfDono = new JComboBox();
		jButton1 = new javax.swing.JButton();
		jBTNCadastrar = new javax.swing.JButton();
		jBTNCadastrar.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				cadastrarPet();
			}
		});
		jLabel4 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

		jTFNome.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTFNomeActionPerformed(evt);
			}
		});

		jButton1.setIcon(new ImageIcon(telaCadastrarPet.class.getResource("/imagens/de-volta.png"))); // NOI18N
		jButton1.setText("Voltar");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jBTNCadastrar.setIcon(new ImageIcon(telaCadastrarPet.class.getResource("/imagens/salvar.png"))); // NOI18N
		jBTNCadastrar.setText("Salvar");

		jLabel4.setText("Sexo:");

		jLabel2.setText("Raça:");

		jLabel1.setText("Nome:");

		jLabel5.setText("CPF Dono:");

		jLabel6.setText("Especie:");

		jTFSexo = new JTextField();
		jTFSexo.setColumns(10);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(jLabel4)
								.addComponent(jLabel2)
								.addComponent(jLabel1)
								.addComponent(jLabel5)
								.addComponent(jLabel6))
						.addPreferredGap(ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(jTFNome, GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
								.addComponent(jCBCpfDono, 0, 169, Short.MAX_VALUE)
								.addComponent(jTFRaca, GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
								.addComponent(jTFEspecie, GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
								.addComponent(jTFSexo))
						.addContainerGap(72, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(38)
						.addComponent(jBTNCadastrar)
						.addPreferredGap(ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
						.addComponent(jButton1)
						.addGap(53))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jCBCpfDono, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel5))
						.addGap(18)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jTFNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1))
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jTFRaca, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2))
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jLabel4)
								.addComponent(jTFSexo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(18)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jTFEspecie, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel6))
						.addGap(19)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jButton1)
								.addComponent(jBTNCadastrar))
						.addContainerGap(27, Short.MAX_VALUE))
				);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);

		pack();
	}// </editor-fold>                        

	private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {                                        
		// TODO add your handling code here:
	}                                       

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:
		telaCadastrarPet.this.dispose();
		main frame = new main();
		frame.setVisible(true);
	}      

	public void PreencherCombo() {
		try {
			ClienteDAO cliente = new ClienteDAO();

			for (Cliente c : cliente.comboMostra()) {
				jCBCpfDono.addItem(c.getCpf());
			}
		} catch (ExceptionDAO | SQLException e) {
			e.printStackTrace();
		}
	}

	public void cadastrarPet() {
		boolean sucesso;
		try {
			ClienteControl clienteControl = new ClienteControl();

			String nome = jTFNome.getText();
			String raca = jTFRaca.getText();
			String especie = jTFEspecie.getText();
			String sexo = jTFSexo.getText();
			if(!sexo.equalsIgnoreCase("masculino")||sexo.equalsIgnoreCase("feminino")) {
				JOptionPane.showMessageDialog(null, "O sexo tem que ser Feminino ou Masculino");
			}else {

				String cboValor2 =  (String) jCBCpfDono.getSelectedItem();
				sucesso = AnimaisControl.cadastrarAnimais(nome, raca, sexo, especie,  (cboValor2) );
				System.out.println(sucesso);
				if (sucesso == true) {
					JOptionPane.showMessageDialog(null, "Pet cadastrado com sucesso");
				} else if (nome.length() <= 0 || raca.length() <= 0 || especie.length() <= 0 || sexo.length() <= 0 
						|| cboValor2 == null) {
					JOptionPane.showMessageDialog(null, "Preencha todos os campos");
				} 
			}
		} catch (Exception ex) {
			ex.printStackTrace();
			JOptionPane.showMessageDialog(null, "Erro ao cadastrar pet");
		}
	}

	/**
	 * @param args the command line arguments
	 */
	//    public static void main(String args[]) {
	//        /* Set the Nimbus look and feel */
	//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	//         */
	//        try {
	//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	//                if ("Nimbus".equals(info.getName())) {
	//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	//                    break;
	//                }
	//            }
	//        } catch (ClassNotFoundException ex) {
	//            java.util.logging.Logger.getLogger(telaCadastrarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	//        } catch (InstantiationException ex) {
	//            java.util.logging.Logger.getLogger(telaCadastrarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	//        } catch (IllegalAccessException ex) {
	//            java.util.logging.Logger.getLogger(telaCadastrarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	//            java.util.logging.Logger.getLogger(telaCadastrarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	//        }
	//        //</editor-fold>
	//
	//        /* Create and display the form */
	//        java.awt.EventQueue.invokeLater(new Runnable() {
	//            public void run() {
	//                new telaCadastrarPet().setVisible(true);
	//            }
	//        });
	//    }

	// Variables declaration - do not modify                     
	private javax.swing.JButton jBTNCadastrar;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTFEspecie;
	private javax.swing.JTextField jTFNome;
	private javax.swing.JTextField jTFRaca;
	private JTextField jTFSexo;
}
